### ISSUE TITLE
Up and down keys should scroll the model list

### ISSUE THREAD

**Issue by jgillard** [rajasimon/django-command-palette#4]
Pretty straightforward feature: when there are multiple options, it'd be great to use the arrow keys to scroll the list before hitting enter. I'm happy to PR this unless you want to.

**Comment by rajasimon** [comment]
@jgillard Thanks for the feature request. I initially thought you can do that but the JS code bit of messy right now and I have to figure out a way to stablize it. 

Meanwhile enjoy the latest release that support the scroll up and down using the arrow key. 

https://github.com/rajasimon/django-command-palette/releases/tag/2022.11.17

**Comment by jgillard** [comment]
Good stuff!

I'd actually already had a go at it, and the one thing I did better I think is the scroll behaviour, which uses `scrollIntoView` rather than pixel offsets, and also allows the selected element to not always be the top option, it's a more natural scroll I think. The code isn't finished but I thought it'd be worth sharing: https://github.com/rajasimon/django-command-palette/commit/880477c51e2da16180d70b723837d1cf36846ed6#diff-a81e8f13f46f86f7b42c8cbdd0eddce9878d66653756b03ad0e8a11007dbb37cR187

Yours:
![Screen Recording 2022-11-17 at 16 44 25](https://user-images.githubusercontent.com/3770312/202507072-9f7fd18a-11c3-4958-b854-90bf7cab61b9.gif)


Mine:
![Screen Recording 2022-11-17 at 16 45 46](https://user-images.githubusercontent.com/3770312/202507018-30d8a785-b921-4e5d-a591-375f17c9d991.gif)

**Comment by rajasimon** [comment]
Yours is way cooler... Can you just make a PR I will accept it right away :)
