### ISSUE TITLE
Chrome on Windows already uses Ctrl + k

### ISSUE THREAD

**Issue by jgillard** [rajasimon/django-command-palette#8]
This may affect other browsers also but I've only tested with Chrome. Palette's keyboard shortcut is already used for a Chrome feature, so it's currently impossible to use your app. It's documented here: https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Caddress-bar-shortcuts:~:text=Search%20from%20anywhere%20on%20the%20page

I'm not sure what the best solution to this is. I tried using preventDefault and stopPropagation but it didn't work for me. I found a discussion about this same key combo here: https://github.com/orgs/community/discussions/24057#discussion-4250265

**Comment by rajasimon** [comment]
Does Github `command + K` works in your Chrome ?

**Comment by jgillard** [comment]
From my testing: yes for Chrome on MacOS, no for both Chrome and Edge on Windows.

**Comment by rajasimon** [comment]
I think it's best to include `ctrl + option + k` for those places `ctrl + k` not work. Do you think that is double ?
